name: type_react
description: A Flutter-Style static typing react.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  react:

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
