name: type_react
description: A Flutter-Style static typing react.
repository: https://github.com/cdfq152313/type_react
version: 0.3.0

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  react:

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
