name: type_react_codegen
description: Code generation for type react.
version: 0.0.1

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  type_react:
    git:
      url: https://github.com/cdfq152313/type_react
      path: type_react
      ref: v0.0.1
  source_gen:
  analyzer:

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
