name: type_react_codegen_example
description: example.
version: 1.0.0

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  type_react:
    path: ../../type_react

dev_dependencies:
  type_react_codegen:
    path: ../
  build_runner:
  build_web_compilers:
  lints: ^1.0.0
  test: ^1.16.0

dependency_overrides:
  type_react:
    path: ../../type_react
